# Generated by Django 5.0.4 on 2024-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField()),
                ('question_2', models.IntegerField()),
                ('question_3', models.IntegerField()),
                ('question_4', models.IntegerField()),
                ('question_5', models.IntegerField()),
                ('question_6', models.IntegerField()),
                ('question_7', models.IntegerField()),
                ('question_8', models.IntegerField()),
                ('question_9', models.IntegerField()),
                ('question_10', models.IntegerField()),
                ('question_11', models.IntegerField()),
                ('question_12', models.IntegerField()),
            ],
        ),
    ]
